[toolchain]
anchor_version = "0.30.0"


[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow_q3 = "4XG5pKaYv3Q479DQUxDQFubvzcSwyLeGnLSWmcWqXY7X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
